package com.siemens.ctbav.intership.shop.service.util.recommandation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-02-23T16:44:22.680+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://RecommandService", name = "RecommandService")
@XmlSeeAlso({ObjectFactory.class})
public interface RecommandService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRecommandation", targetNamespace = "http://RecommandService", className = "com.siemens.ctbav.intership.shop.service.util.recommandation.GetRecommandation")
    @WebMethod
    @ResponseWrapper(localName = "getRecommandationResponse", targetNamespace = "http://RecommandService", className = "com.siemens.ctbav.intership.shop.service.util.recommandation.GetRecommandationResponse")
    public java.util.List<java.lang.Long> getRecommandation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "writePreferences", targetNamespace = "http://RecommandService", className = "com.siemens.ctbav.intership.shop.service.util.recommandation.WritePreferences")
    @WebMethod
    @ResponseWrapper(localName = "writePreferencesResponse", targetNamespace = "http://RecommandService", className = "com.siemens.ctbav.intership.shop.service.util.recommandation.WritePreferencesResponse")
    public void writePreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.Long> arg1
    );
}
